<?php
/**
 * Item
 *
 * PHP version 5
 *
 * @category Class
 * @package  DataExchange\SIFUK20
 * @author   DataExchange team
 * @link     https://developer.dataexchange.education
 */

/**
 * SIF (UK), v.2.0
 *
 * OpenAPI specification for the SIF (UK), v.2.0 data model. Generated by DataExchange (dataexchange.educaton) at 2017-08-13 19:14:57
 *
 * OpenAPI spec version: 1.0.0.20170813191457
 * Contact: support@dataexchange.education
 * Generated by: https://developer.dataexchange.education
 *
 */

/**
 * NOTE: This class is auto generated.
 * https://developer.dataexchange.education
 * Do not edit the class manually.
 */

namespace DataExchange\SIFUK20\Models;

use \ArrayAccess;

/**
 * Item Class Doc Comment
 *
 * @category    Class
 * @package     DataExchange\SIFUK20
 * @author      DataExchange team
 * @link        https://developer.dataexchange.education
 */
class Item implements ArrayAccess
{
    const DISCRIMINATOR = null;

    const IS_ARRAY = false;
    const ITEMS = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Item';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'response' => 'string',
        'response_status' => 'string',
        'response_time' => 'string',
        'mark' => 'string',
        'group' => 'string',
        'item_name' => 'string',
        'item_number' => 'string',
        'order_asked' => 'double',
        'number_of_attempts' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'response' => null,
        'response_status' => null,
        'response_time' => null,
        'mark' => null,
        'group' => null,
        'item_name' => null,
        'item_number' => null,
        'order_asked' => 'double',
        'number_of_attempts' => 'int64'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'response' => 'Response',
        'response_status' => 'ResponseStatus',
        'response_time' => 'ResponseTime',
        'mark' => 'Mark',
        'group' => 'Group',
        'item_name' => 'ItemName',
        'item_number' => 'ItemNumber',
        'order_asked' => 'OrderAsked',
        'number_of_attempts' => 'NumberOfAttempts'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'response' => 'setResponse',
        'response_status' => 'setResponseStatus',
        'response_time' => 'setResponseTime',
        'mark' => 'setMark',
        'group' => 'setGroup',
        'item_name' => 'setItemName',
        'item_number' => 'setItemNumber',
        'order_asked' => 'setOrderAsked',
        'number_of_attempts' => 'setNumberOfAttempts'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'response' => 'getResponse',
        'response_status' => 'getResponseStatus',
        'response_time' => 'getResponseTime',
        'mark' => 'getMark',
        'group' => 'getGroup',
        'item_name' => 'getItemName',
        'item_number' => 'getItemNumber',
        'order_asked' => 'getOrderAsked',
        'number_of_attempts' => 'getNumberOfAttempts'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['response'] = isset($data['response']) ? $data['response'] : null;
        $this->container['response_status'] = isset($data['response_status']) ? $data['response_status'] : null;
        $this->container['response_time'] = isset($data['response_time']) ? $data['response_time'] : null;
        $this->container['mark'] = isset($data['mark']) ? $data['mark'] : null;
        $this->container['group'] = isset($data['group']) ? $data['group'] : null;
        $this->container['item_name'] = isset($data['item_name']) ? $data['item_name'] : null;
        $this->container['item_number'] = isset($data['item_number']) ? $data['item_number'] : null;
        $this->container['order_asked'] = isset($data['order_asked']) ? $data['order_asked'] : null;
        $this->container['number_of_attempts'] = isset($data['number_of_attempts']) ? $data['number_of_attempts'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['response'] === null) {
            $invalid_properties[] = "'response' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['response'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets response
     * @return string
     */
    public function getResponse()
    {
        return isset($this->container['response']) ? $this->container['response'] : null;
    }

    /**
     * Sets response
     * @param string $response Learner selection or response in raw format.
     * @return $this
     */
    public function setResponse($response)
    {
        $this->container['response'] = $response;

        return $this;
    }

    /**
     * Gets response_status
     * @return string
     */
    public function getResponseStatus()
    {
        return isset($this->container['response_status']) ? $this->container['response_status'] : null;
    }

    /**
     * Sets response_status
     * @param string $response_status Status of the response.
     * @return $this
     */
    public function setResponseStatus($response_status)
    {
        $this->container['response_status'] = $response_status;

        return $this;
    }

    /**
     * Gets response_time
     * @return string
     */
    public function getResponseTime()
    {
        return isset($this->container['response_time']) ? $this->container['response_time'] : null;
    }

    /**
     * Sets response_time
     * @param string $response_time The length of time the learner took to respond.
     * @return $this
     */
    public function setResponseTime($response_time)
    {
        $this->container['response_time'] = $response_time;

        return $this;
    }

    /**
     * Gets mark
     * @return string
     */
    public function getMark()
    {
        return isset($this->container['mark']) ? $this->container['mark'] : null;
    }

    /**
     * Sets mark
     * @param string $mark The mark achieved for this item as evaluated by the assessment tool at the time of assessment.
     * @return $this
     */
    public function setMark($mark)
    {
        $this->container['mark'] = $mark;

        return $this;
    }

    /**
     * Gets group
     * @return string
     */
    public function getGroup()
    {
        return isset($this->container['group']) ? $this->container['group'] : null;
    }

    /**
     * Sets group
     * @param string $group The item group within the assessment.
     * @return $this
     */
    public function setGroup($group)
    {
        $this->container['group'] = $group;

        return $this;
    }

    /**
     * Gets item_name
     * @return string
     */
    public function getItemName()
    {
        return isset($this->container['item_name']) ? $this->container['item_name'] : null;
    }

    /**
     * Sets item_name
     * @param string $item_name Identifies the item on the assessment by name.
     * @return $this
     */
    public function setItemName($item_name)
    {
        $this->container['item_name'] = $item_name;

        return $this;
    }

    /**
     * Gets item_number
     * @return string
     */
    public function getItemNumber()
    {
        return isset($this->container['item_number']) ? $this->container['item_number'] : null;
    }

    /**
     * Sets item_number
     * @param string $item_number Identifies the item by number on the assessment.
     * @return $this
     */
    public function setItemNumber($item_number)
    {
        $this->container['item_number'] = $item_number;

        return $this;
    }

    /**
     * Gets order_asked
     * @return double
     */
    public function getOrderAsked()
    {
        return isset($this->container['order_asked']) ? $this->container['order_asked'] : null;
    }

    /**
     * Sets order_asked
     * @param double $order_asked The order in which the item was asked.
     * @return $this
     */
    public function setOrderAsked($order_asked)
    {
        $this->container['order_asked'] = $order_asked;

        return $this;
    }

    /**
     * Gets number_of_attempts
     * @return int
     */
    public function getNumberOfAttempts()
    {
        return isset($this->container['number_of_attempts']) ? $this->container['number_of_attempts'] : null;
    }

    /**
     * Sets number_of_attempts
     * @param int $number_of_attempts The number of times a learner changes their answer or attempts a response.
     * @return $this
     */
    public function setNumberOfAttempts($number_of_attempts)
    {
        $this->container['number_of_attempts'] = $number_of_attempts;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object in JSON format
     * @return string
     */
    public function toJson()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\DataExchange\SIFUK20\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\DataExchange\SIFUK20\ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object in XML format
     * @return string
     */
    public function toXml()
    {
        $dom = new \DOMDocument();

        $node = $dom->importNode($this->toXmlNode(), true);

        $dom->preserveWhiteSpace = false;
        $dom->formatOutput = true;
        $xml = $dom->saveXML($node);

        unset($node);
        unset($dom);

        return $xml;
    }

    /**
     * Gets the string presentation of the object in XML format
     * @return string
     */
    public function toXmlNode()
    {
        $dom = new \DOMDocument();
        $elem = $dom->createElement(self::$swaggerModelName);

        foreach (self::attributeMap() as $key => $property) {
            $value = $this->{$this->getters()[$key]}();

            if (is_null($value)) {
                // Do nothing
                continue;
            }

            if ($property[0] === '@') {
                $elem->setAttribute(substr($property, 1), $value);
            } else {
                if (is_scalar($value)) {
                    $elem->appendChild($dom->createElement($property, $value));
                } elseif ($value instanceof \DateTime) {
                    $format = $this->swaggerFormats()[$key];
                    $str = ($format === 'date') ? $value->format('Y-m-d') : $value->format(\DateTime::ATOM);
                    $elem->appendChild($dom->createElement($property, $str));
                } elseif (is_array($value)) {
                    if (is_scalar($value)) {
                        // TODO
                        /*
                        foreach ($value as $property => $value) {
                            $elem->appendChild($dom->createElement($property, (string) $value));
                        }
                        */
                    } else {
                        // TODO
                        /*
                        foreach ($value as $property => $value) {
                            $elem->appendChild($dom->importNode($value->toXmlNode(), true));
                            // $elem->appendChild($dom->createElement($property, (string) $value));
                        }
                        */
                    }
                } elseif (is_object($value)) {
                    $elem->appendChild($dom->importNode($value->toXmlNode(), true));
                } else {
                    $elem->appendChild($dom->createElement($property, (string) $value));
                }
            }
        }

        if (self::IS_ARRAY) {
            foreach ($this->container as $key => $item) {
                $elem->appendChild($dom->importNode($item->toXmlNode(), true));
            }
        }

        return $elem;
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        return $this->toXml();
    }
}


