<?php
/**
 * AssessmentResultComponentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DataExchange\SIFUK20
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SIF (UK), v.2.0
 *
 * DataExchange for the SIF (UK), v.2.0 data model
 *
 * OpenAPI spec version: 1.0
 * Contact: support@dataexchange.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DataExchange\SIFUK20;

/**
 * AssessmentResultComponentTest Class Doc Comment
 *
 * @category    Class */
// * @description A psychological construct measured by the assessment. Operationally, an assessment component or subtest is a class of scores within an assessment that might collectively represent a column within a mark book. Some assessments may consist of only one component, aspect or subtest although it is more common for assessments to have several.
/**
 * @package     DataExchange\SIFUK20
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AssessmentResultComponentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AssessmentResultComponent"
     */
    public function testAssessmentResultComponent()
    {

    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "local_id"
     */
    public function testPropertyLocalId()
    {

    }

    /**
     * Test attribute "short_description"
     */
    public function testPropertyShortDescription()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "year_list"
     */
    public function testPropertyYearList()
    {

    }

    /**
     * Test attribute "assessment_subject_list"
     */
    public function testPropertyAssessmentSubjectList()
    {

    }

    /**
     * Test attribute "stage_list"
     */
    public function testPropertyStageList()
    {

    }

    /**
     * Test attribute "assessment_result_grade_set_ref_id"
     */
    public function testPropertyAssessmentResultGradeSetRefId()
    {

    }

    /**
     * Test attribute "mark_set_list"
     */
    public function testPropertyMarkSetList()
    {

    }

    /**
     * Test attribute "component_type"
     */
    public function testPropertyComponentType()
    {

    }

    /**
     * Test attribute "result_qualifier"
     */
    public function testPropertyResultQualifier()
    {

    }

    /**
     * Test attribute "assessment_method"
     */
    public function testPropertyAssessmentMethod()
    {

    }

    /**
     * Test attribute "supplier_name"
     */
    public function testPropertySupplierName()
    {

    }

}
