<?php
/**
 * ContactFlagsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DataExchange\SIFUK20
 * @author   DataExchange team
 * @link     https://developer.dataexchange.education
 */

/**
 * SIF (UK), v.2.0
 *
 * OpenAPI specification for the SIF (UK), v.2.0 data model. Generated by DataExchange (dataexchange.educaton) at 2017-08-13 19:14:57
 *
 * OpenAPI spec version: 1.0.0.20170813191457
 * Contact: support@dataexchange.education
 * Generated by: https://developer.dataexchange.education
 *
 */

/**
 * NOTE: This class is auto generated.
 * https://developer.dataexchange.education
 * Please update the test case below to test the model.
 */

namespace DataExchange\SIFUK20;

/**
 * ContactFlagsTest Class Doc Comment
 *
 * @category    Class */
// * @description ContactFlags
/**
 * @package     DataExchange\SIFUK20
 * @author      DataExchange team
 * @link        https://developer.dataexchange.education
 */
class ContactFlagsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ContactFlags"
     */
    public function testContactFlags()
    {
    }

    /**
     * Test attribute "parent_legal_guardian"
     */
    public function testPropertyParentLegalGuardian()
    {
    }

    /**
     * Test attribute "pickup_rights"
     */
    public function testPropertyPickupRights()
    {
    }

    /**
     * Test attribute "lives_with"
     */
    public function testPropertyLivesWith()
    {
    }

    /**
     * Test attribute "address_disclosure"
     */
    public function testPropertyAddressDisclosure()
    {
    }

    /**
     * Test attribute "email_communication"
     */
    public function testPropertyEmailCommunication()
    {
    }

    /**
     * Test attribute "emergency_contact"
     */
    public function testPropertyEmergencyContact()
    {
    }

    /**
     * Test attribute "disciplinary_contact"
     */
    public function testPropertyDisciplinaryContact()
    {
    }

    /**
     * Test attribute "home_during_day"
     */
    public function testPropertyHomeDuringDay()
    {
    }

    /**
     * Test attribute "member_of_armed_forces"
     */
    public function testPropertyMemberOfArmedForces()
    {
    }

    /**
     * Test attribute "primary_care_provider"
     */
    public function testPropertyPrimaryCareProvider()
    {
    }

    /**
     * Test attribute "requires_interpreter"
     */
    public function testPropertyRequiresInterpreter()
    {
    }

    /**
     * Test attribute "transfer_address"
     */
    public function testPropertyTransferAddress()
    {
    }
}
