<?php
/**
 * JunctionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DataExchange\SIFUK20
 * @author   DataExchange team
 * @link     https://developer.dataexchange.education
 */

/**
 * SIF (UK), v.2.0
 *
 * OpenAPI specification for the SIF (UK), v.2.0 data model. Generated by DataExchange (dataexchange.educaton) at 2017-08-13 19:14:57
 *
 * OpenAPI spec version: 1.0.0.20170813191457
 * Contact: support@dataexchange.education
 * Generated by: https://developer.dataexchange.education
 *
 */

/**
 * NOTE: This class is auto generated.
 * https://developer.dataexchange.education
 * Please update the test case below to test the model.
 */

namespace DataExchange\SIFUK20;

/**
 * JunctionTest Class Doc Comment
 *
 * @category    Class */
// * @description A representation of the Curriculum Diagram.
/**
 * @package     DataExchange\SIFUK20
 * @author      DataExchange team
 * @link        https://developer.dataexchange.education
 */
class JunctionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Junction"
     */
    public function testJunction()
    {
    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "short_label"
     */
    public function testPropertyShortLabel()
    {
    }

    /**
     * Test attribute "local_type"
     */
    public function testPropertyLocalType()
    {
    }

    /**
     * Test attribute "input_list"
     */
    public function testPropertyInputList()
    {
    }

    /**
     * Test attribute "output_list"
     */
    public function testPropertyOutputList()
    {
    }
}
