<?php
/**
 * LearnerSchoolEnrolmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DataExchange\UK\20
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SIF (UK), v.2.0
 *
 * DataExchange for the SIF (UK), v.2.0 data model
 *
 * OpenAPI spec version: 1.0
 * Contact: support@zinethq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DataExchange\UK\20;

/**
 * LearnerSchoolEnrolmentTest Class Doc Comment
 *
 * @category    Class */
// * @description This object defines information related to a learner&amp;#039;s enrolment within a particular school or establishment.The current status on an enrolment is based on EntryDate and ExitDate. Future enrolments are supported where EntryDate is in the future. ExitDate may also be specified as a future occurance.
/**
 * @package     DataExchange\UK\20
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LearnerSchoolEnrolmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "LearnerSchoolEnrolment"
     */
    public function testLearnerSchoolEnrolment()
    {

    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {

    }

    /**
     * Test attribute "learner_personal_ref_id"
     */
    public function testPropertyLearnerPersonalRefId()
    {

    }

    /**
     * Test attribute "school_info_ref_id"
     */
    public function testPropertySchoolInfoRefId()
    {

    }

    /**
     * Test attribute "membership_type"
     */
    public function testPropertyMembershipType()
    {

    }

    /**
     * Test attribute "entry_date"
     */
    public function testPropertyEntryDate()
    {

    }

    /**
     * Test attribute "nc_year_group_actual"
     */
    public function testPropertyNcYearGroupActual()
    {

    }

    /**
     * Test attribute "class_type"
     */
    public function testPropertyClassType()
    {

    }

    /**
     * Test attribute "exit_date"
     */
    public function testPropertyExitDate()
    {

    }

    /**
     * Test attribute "exit_type"
     */
    public function testPropertyExitType()
    {

    }

    /**
     * Test attribute "sessions"
     */
    public function testPropertySessions()
    {

    }

    /**
     * Test attribute "ftpt_status"
     */
    public function testPropertyFtptStatus()
    {

    }

    /**
     * Test attribute "boarder"
     */
    public function testPropertyBoarder()
    {

    }

    /**
     * Test attribute "alternative_tuition"
     */
    public function testPropertyAlternativeTuition()
    {

    }

}
