<?php
/**
 * LearnerExclusionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DataExchange\SIFUK20
 * @author   DataExchange team
 * @link     https://developer.dataexchange.education
 */

/**
 * SIF (UK), v.2.0
 *
 * OpenAPI specification for the SIF (UK), v.2.0 data model. Generated by DataExchange (dataexchange.educaton) at 2017-08-13 19:14:57
 *
 * OpenAPI spec version: 1.0.0.20170813191457
 * Contact: support@dataexchange.education
 * Generated by: https://developer.dataexchange.education
 *
 */

/**
 * NOTE: This class is auto generated.
 * https://developer.dataexchange.education
 * Please update the test case below to test the model.
 */

namespace DataExchange\SIFUK20;

/**
 * LearnerExclusionTest Class Doc Comment
 *
 * @category    Class */
// * @description This object contains information related to a learner being excluded from one or more sessions of school.
/**
 * @package     DataExchange\SIFUK20
 * @author      DataExchange team
 * @link        https://developer.dataexchange.education
 */
class LearnerExclusionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LearnerExclusion"
     */
    public function testLearnerExclusion()
    {
    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {
    }

    /**
     * Test attribute "learner_personal_ref_id"
     */
    public function testPropertyLearnerPersonalRefId()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "start_session"
     */
    public function testPropertyStartSession()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "actual_sessions"
     */
    public function testPropertyActualSessions()
    {
    }

    /**
     * Test attribute "appeal"
     */
    public function testPropertyAppeal()
    {
    }

    /**
     * Test attribute "appeal_date"
     */
    public function testPropertyAppealDate()
    {
    }

    /**
     * Test attribute "appeal_result"
     */
    public function testPropertyAppealResult()
    {
    }

    /**
     * Test attribute "reinstatement_date"
     */
    public function testPropertyReinstatementDate()
    {
    }

    /**
     * Test attribute "head_teacher_notification_date"
     */
    public function testPropertyHeadTeacherNotificationDate()
    {
    }

    /**
     * Test attribute "governor_meeting_date"
     */
    public function testPropertyGovernorMeetingDate()
    {
    }

    /**
     * Test attribute "hearing_notice_of_appeal_date"
     */
    public function testPropertyHearingNoticeOfAppealDate()
    {
    }
}
