<?php
/**
 * LearnerGroupEnrolmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DataExchange\SIFUK20
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SIF (UK), v.2.0
 *
 * DataExchange for the SIF (UK), v.2.0 data model
 *
 * OpenAPI spec version: 1.0
 * Contact: support@zinethq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DataExchange\SIFUK20;

/**
 * LearnerGroupEnrolmentTest Class Doc Comment
 *
 * @category    Class */
// * @description This object contains information about a learner&amp;#039;s enrolment in a course (teaching group) or other (class, homeroom or registration) group. Compare with US/Canada object:
/**
 * @package     DataExchange\SIFUK20
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LearnerGroupEnrolmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "LearnerGroupEnrolment"
     */
    public function testLearnerGroupEnrolment()
    {

    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {

    }

    /**
     * Test attribute "learner_personal_ref_id"
     */
    public function testPropertyLearnerPersonalRefId()
    {

    }

    /**
     * Test attribute "school_group_ref_id"
     */
    public function testPropertySchoolGroupRefId()
    {

    }

    /**
     * Test attribute "school_year"
     */
    public function testPropertySchoolYear()
    {

    }

    /**
     * Test attribute "entry_date"
     */
    public function testPropertyEntryDate()
    {

    }

    /**
     * Test attribute "exit_date"
     */
    public function testPropertyExitDate()
    {

    }

}
