<?php
/**
 * LessonTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DataExchange\SIFUK20
 * @author   DataExchange team
 * @link     https://developer.dataexchange.education
 */

/**
 * SIF (UK), v.2.0
 *
 * OpenAPI specification for the SIF (UK), v.2.0 data model. Generated by DataExchange (dataexchange.educaton) at 2017-08-13 19:14:57
 *
 * OpenAPI spec version: 1.0.0.20170813191457
 * Contact: support@dataexchange.education
 * Generated by: https://developer.dataexchange.education
 *
 */

/**
 * NOTE: This class is auto generated.
 * https://developer.dataexchange.education
 * Please update the test case below to test the model.
 */

namespace DataExchange\SIFUK20;

/**
 * LessonTest Class Doc Comment
 *
 * @category    Class */
// * @description A lesson on the timetable
/**
 * @package     DataExchange\SIFUK20
 * @author      DataExchange team
 * @link        https://developer.dataexchange.education
 */
class LessonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Lesson"
     */
    public function testLesson()
    {
    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {
    }

    /**
     * Test attribute "cycle_ref_id"
     */
    public function testPropertyCycleRefId()
    {
    }

    /**
     * Test attribute "tt_day_id"
     */
    public function testPropertyTtDayId()
    {
    }

    /**
     * Test attribute "period_index"
     */
    public function testPropertyPeriodIndex()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {
    }

    /**
     * Test attribute "teaching_group_ref_id"
     */
    public function testPropertyTeachingGroupRefId()
    {
    }

    /**
     * Test attribute "nt_code_ref"
     */
    public function testPropertyNtCodeRef()
    {
    }

    /**
     * Test attribute "teacher_list"
     */
    public function testPropertyTeacherList()
    {
    }

    /**
     * Test attribute "tt_room_ref_id"
     */
    public function testPropertyTtRoomRefId()
    {
    }

    /**
     * Test attribute "sif_extended_elements"
     */
    public function testPropertySifExtendedElements()
    {
    }
}
