<?php
/**
 * SchoolGroupTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DataExchange\SIFUK20
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SIF (UK), v.2.0
 *
 * DataExchange for the SIF (UK), v.2.0 data model
 *
 * OpenAPI spec version: 1.0
 * Contact: support@dataexchange.education
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DataExchange\SIFUK20;

/**
 * SchoolGroupTest Class Doc Comment
 *
 * @category    Class */
// * @description This object describes a specific group and includes resource and time tabling information. All groups are based upon a SchoolGroupType record. However, there are courses which are not based upon any subject area and likewise may not have any teachers or other staff assigned. Compare with US/Canada object:
/**
 * @package     DataExchange\SIFUK20
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SchoolGroupTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "SchoolGroup"
     */
    public function testSchoolGroup()
    {

    }

    /**
     * Test attribute "ref_id"
     */
    public function testPropertyRefId()
    {

    }

    /**
     * Test attribute "school_group_type_ref_id"
     */
    public function testPropertySchoolGroupTypeRefId()
    {

    }

    /**
     * Test attribute "school_year"
     */
    public function testPropertySchoolYear()
    {

    }

    /**
     * Test attribute "local_id"
     */
    public function testPropertyLocalId()
    {

    }

    /**
     * Test attribute "group_name"
     */
    public function testPropertyGroupName()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "parent_school_group_ref_id"
     */
    public function testPropertyParentSchoolGroupRefId()
    {

    }

    /**
     * Test attribute "schedule_info_list"
     */
    public function testPropertyScheduleInfoList()
    {

    }

}
