<?php
/**
 * AttendanceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DataExchange\UK\20
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SIF (UK), v.2.0
 *
 * DataExchange for the SIF (UK), v.2.0 data model
 *
 * OpenAPI spec version: 1.0
 * Contact: support@zinethq.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DataExchange\UK\20;

use \DataExchange\UK\20\Configuration;
use \DataExchange\UK\20\ApiClient;
use \DataExchange\UK\20\ApiException;
use \DataExchange\UK\20\ObjectSerializer;

/**
 * AttendanceApiTest Class Doc Comment
 *
 * @category Class
 * @package  DataExchange\UK\20
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AttendanceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createLearnerAttendanceSummarys
     *
     * Create multiple LearnerAttendanceSummarys.
     *
     */
    public function testCreateLearnerAttendanceSummarys()
    {

    }

    /**
     * Test case for createLearnerAttendances
     *
     * Create multiple LearnerAttendances.
     *
     */
    public function testCreateLearnerAttendances()
    {

    }

    /**
     * Test case for deleteLearnerAttendanceByRefId
     *
     * Delete LearnerAttendance by RefId.
     *
     */
    public function testDeleteLearnerAttendanceByRefId()
    {

    }

    /**
     * Test case for deleteLearnerAttendanceSummaryByRefId
     *
     * Delete LearnerAttendanceSummary by RefId.
     *
     */
    public function testDeleteLearnerAttendanceSummaryByRefId()
    {

    }

    /**
     * Test case for deleteLearnerAttendanceSummarys
     *
     * Delete multiple LearnerAttendanceSummarys.
     *
     */
    public function testDeleteLearnerAttendanceSummarys()
    {

    }

    /**
     * Test case for deleteLearnerAttendances
     *
     * Delete multiple LearnerAttendances.
     *
     */
    public function testDeleteLearnerAttendances()
    {

    }

    /**
     * Test case for getLearnerAttendanceByRefId
     *
     * Find LearnerAttendance by RefId.
     *
     */
    public function testGetLearnerAttendanceByRefId()
    {

    }

    /**
     * Test case for getLearnerAttendanceSummaryByRefId
     *
     * Find LearnerAttendanceSummary by RefId.
     *
     */
    public function testGetLearnerAttendanceSummaryByRefId()
    {

    }

    /**
     * Test case for getLearnerAttendanceSummarys
     *
     * Return all LearnerAttendanceSummarys.
     *
     */
    public function testGetLearnerAttendanceSummarys()
    {

    }

    /**
     * Test case for getLearnerAttendances
     *
     * Return all LearnerAttendances.
     *
     */
    public function testGetLearnerAttendances()
    {

    }

    /**
     * Test case for updateLearnerAttendanceByRefId
     *
     * Update LearnerAttendance by RefId.
     *
     */
    public function testUpdateLearnerAttendanceByRefId()
    {

    }

    /**
     * Test case for updateLearnerAttendanceSummaryByRefId
     *
     * Update LearnerAttendanceSummary by RefId.
     *
     */
    public function testUpdateLearnerAttendanceSummaryByRefId()
    {

    }

    /**
     * Test case for updateLearnerAttendanceSummarys
     *
     * Update multiple LearnerAttendanceSummarys.
     *
     */
    public function testUpdateLearnerAttendanceSummarys()
    {

    }

    /**
     * Test case for updateLearnerAttendances
     *
     * Update multiple LearnerAttendances.
     *
     */
    public function testUpdateLearnerAttendances()
    {

    }

}
